// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function resolveDatabaseUrl(): string {
  const candidates = [
    process.env.DATABASE_URL,
    process.env.POSTGRES_URL_NON_POOLING,
    process.env.POSTGRES_URL,
  ].filter(Boolean) as string[];

  const url = candidates.find((u) => /^postgres(ql)?:\/\//.test(u));
  if (url) return url;
  // During Vercel install, env vars may not be injected yet.
  // Provide a valid-scheme placeholder so `prisma generate` can proceed.
  return "postgresql://placeholder.invalid/postgres?sslmode=require";
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: resolveDatabaseUrl(),
  },
});
