// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function resolveDatabaseUrl(): string {
  const candidates = [
    process.env.DATABASE_URL,
    process.env.POSTGRES_URL_NON_POOLING,
    process.env.POSTGRES_URL,
  ].filter(Boolean) as string[];

  const url = candidates.find((u) => /^postgres(ql)?:\/\//.test(u));
  if (!url) {
    throw new Error(
      "Missing or invalid database URL. Set `DATABASE_URL` or expose `POSTGRES_URL_NON_POOLING`/`POSTGRES_URL` with a postgres:// or postgresql:// scheme."
    );
  }
  return url;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: resolveDatabaseUrl(),
  },
});
